services:
    chall:
        build: ./chall
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:80"
        volumes:
            - ./chall/www:/var/www/html:ro

    bot:
        build: ./bot
        restart: unless-stopped
        ports:
            - "127.0.0.1:1337:1337"
        env_file:
            - .env
        environment:
            - DOMAIN=${DOMAIN}
            - FLAG=${FLAG}