SSLProtocol -all +TLSv1 +TLSv1.1 +TLSv1.2 +TLSv1.3
ServerName ${APP_DOMAIN}
KeepAliveTimeout 60
SSLSessionTickets off

<VirtualHost *:443>
    ServerAdmin webmaster@localhost

    DocumentRoot /var/www/html

    CustomLog /dev/stdout combined
    ErrorLog  /dev/stderr

    SSLEngine on

    SSLCertificateFile      /etc/ssl/certs/cert.pem
    SSLCertificateKeyFile   /etc/ssl/private/cert.key

    <Directory /var/www/html>
        Options -Indexes -FollowSymLinks
        AllowOverride None
    </Directory>
</VirtualHost>


<VirtualHost *:80>
    DocumentRoot /var/www/html

    CustomLog /dev/stdout combined
    ErrorLog  /dev/stderr

    SSLEngine Optional

    SSLCertificateFile      /etc/ssl/certs/cert.pem
    SSLCertificateKeyFile   /etc/ssl/private/cert.key

    <Directory /var/www/html>
        Options -Indexes -FollowSymLinks
        AllowOverride None
    </Directory>
</VirtualHost>


Listen 1337
<VirtualHost *:1337>
    SSLEngine off
    ProxyPreserveHost On
    ProxyAddHeaders On
    
    ProxyPass / http://bot:1337/
</VirtualHost>
